### ISSUE TITLE
Updated build instructions?

### ISSUE THREAD

**Issue by jafingerhut** [GlenKPeterson/TestUtils#1]
I found this repository through the README on Paguro, suggesting that this repo should be built before Paguro's.  The instructions there, and in this project's, README for using `mvn` to build appear out of date if I understand correctly, since there is no pom.xml file in this project any longer.

I have toyed with a few experiments trying to use Gradle to build this project, but am new to that build tool and haven't found the proper recipe yet.  If you have any quick pointers or suggestions, I would appreciate it.

**Comment by GlenKPeterson** [comment]
I'm quite new to gradle as well.  I installed gradle using SDKMAN! according to the instructions here:
https://docs.gradle.org/current/userguide/installation.html

You can see what's available by running:
```bash
TestUtils$ ./gradlew tasks
```

I think `gradle clean build publish` will make the result available to other gradle projects, or use `publishToMavenLocal` instead of `publish` to make it available to other mvn projects.

Thanks for letting me know my docs are out of date.  I would welcome a minimal-change pull request, or I'll update them eventually.

I just built with:
```bash
$ gradle -version

------------------------------------------------------------
Gradle 5.6.2
------------------------------------------------------------

Build time:   2019-09-05 16:13:54 UTC
Revision:     55a5e53d855db8fc7b0e494412fc624051a8e781

Kotlin:       1.3.41
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          11.0.4 (Ubuntu 11.0.4+11-post-Ubuntu-1ubuntu218.04.3)
OS:           Linux 4.15.0-66-generic amd64
```

Let me know if that works for you.  Thanks for your interest!

**Comment by GlenKPeterson** [comment]
Upgraded to Gradle 5.6.3 with same result.  Paguro should work with the same commands IIRC.

**Comment by GlenKPeterson** [comment]
Build instructions are now here: https://github.com/GlenKPeterson/TestUtils#contributions
Thanks for pointing this out.  I'm closing this.  Will reopen if you have trouble.
